### ISSUE TITLE
Android 7.x Issue with Video Enrolment / Auth

### ISSUE THREAD

**Issue by niraj-shah** [aimbrain/aimbrain-android-sdk#5]
No matter how bright the screen is set, using Video to Enrol / Auth a user causes the screen to dull on Android Nougat 7.x.

This was tested on Google Pixel XL, running Android 7.1.1. A video demonstrating the issue can be found here: https://youtu.be/NRx5bFdfDrI

Issue does not appear on:
* Samsung S4 Mini, running Android 4.4.2.
* Samsung S7 Edge, running Android 6.0.1

**Comment by alesis** [comment]
We could not replicate the issue on Android 7.1.1. Judging from the comments found online this was a Pixel issue which has since been addressed.
